---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 97556.
--- DateTime: 2023-12-20 16:41
---

--你的验证码在Redis中的key
local key = KEYS[1]
--用户输入的code
local expectedCode = ARGV[1]
local code = redis.call("get",key)
local cntKey = key..":cnt"
--转成一个数字
local cnt = tonumber(redis.call("get",cntKey))

if cnt <=0 then
    --用户一直输错，验证次数已经用完,有人搞你
    --或者已经用过了，有人搞你
    return -1
elseif expectedCode == code then
    --验证成功
    --用完，不能再用了
    redis.call("set",cntKey,cnt-1)
    --redis.call("del",key)
    return 0
else
    --验证失败
    redis.call("decr",cntKey,cnt-1)
    return -2
end