#pvc=>webook-mysql-claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  这个是指我mysql要用的东西
  name: webook-mysql-claim
  labels:
    app: webook-mysql-claim
spec:
#  z这个可以随便命名
  storageClassName: suibian
  accessModes:
#    - 一个(pod)读写
    - ReadWriteOnce
#    - 多个读，一个写
#    - ReadOnlyMany
#    - 多个读写
#    - ReadWriteMany
  resources:
    requests:
#      1 GB
      storage: 1Gi


  