---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenguangyao.
--- DateTime: 2023/12/11 14:39
---
wrk.method="POST"
wrk.headers["Content-Type"] = "application/json"
--这里要改为你注册的数据
wrk.body='{"email":"123o@qq.com","password":"hello@world123"}'