---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenguangyao.
--- DateTime: 2023/12/11 15:36
---
wrk.method="GET"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["User-Agent"] = "PostmanRuntime/7.32.3"
-- 记得修改这个，你在登录页面登录一下，然后复制一个过来这里
wrk.headers["Authorization"]="Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIyODE4OTksIlVpZCI6NCwiVXNlckFnZW50IjoiUG9zdG1hblJ1bnRpbWUvNy4zNS4wIn0.8d3UsbAB6e8dVkihXlxMgzuVetx1-vlpg6V6AwJ-NX9cMc4SuPWpy9aygfjBzMKzpNW4LLPU4EKX8mysCJaB2w"