---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenguangyao.
--- DateTime: 2023/12/11 15:36
---
wrk.method="GET"
wrk.headers["Content-Type"] = "application/json"
wrk.headers["User-Agent"] = "PostmanRuntime/7.35.0"
-- 记得修改这个，你在登录页面登录一下，然后复制一个过来这里
wrk.headers["Authorization"]="Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI0MzgzNTMsIlVpZCI6NCwiVXNlckFnZW50IjoiUG9zdG1hblJ1bnRpbWUvNy4zNS4wIn0.nLwwu57sgEsmO4WQDlOqpBIw5uwZdi-h_arEvQ2XEFLmayyahoo8vOC1AeiU7-e2SrNPmS06FzPT9tLL5huxgQ"